### ISSUE TITLE
Compose envs not loaded while building image

### ISSUE THREAD

**Issue by TigerdieKatze** [Pudl0/guardian-of-orkadatas-secrets#5]
The envs set in the docker compose are not loaded while the build process is running. 

An Idea would be to set build and deploy-commands as a bundled start command.

**Comment by LakayFTW** [comment]
Add this to the Dockerfile below Copy . /guardian/
# Copy .env file
COPY .env .env

And in the docker-compose.yml you had previously written the tokens with these brackets <>.
eg.   `DISCORD_GUILD_ID=<guildId>`

Try this:

```yml
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
```
      
I'll test this this evening or tomorrow. I am just too lazy to set this bot up atm.
